name: Terraform Apply for EC2 Instance

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}                      # set this to your preferred AWS region, e.g. us-west-1
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}                      # set this to your Amazon ECR repository name
  TF_VAR_region: ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Plan Terraform
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply Terraform configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
          
      # Optional: Output EC2 instance details
      - name: Show EC2 Instance ID
        run: terraform output
